# Generated by Django 5.1.1 on 2024-10-23 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_website', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('company_size', models.IntegerField()),
                ('company_address', models.TextField()),
                ('logo', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('phn_no', models.CharField(max_length=10)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Employeers',
            },
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('experience_years', models.IntegerField()),
                ('education', models.TextField()),
                ('expected_salary', models.CharField(max_length=255)),
                ('location_preference', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Looking', 'Looking'), ('Not Looking', 'Not Looking'), ('Closed', 'Closed')], default='Looking', max_length=20)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'JobSeeker',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Employeer', 'Employeer')], default='User', max_length=20)),
                ('phn_no', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('address', models.TextField()),
                ('profile_complete', models.BooleanField()),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='Full-Time', max_length=20)),
                ('salary_range', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(auto_now=True)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_tables.employeers')),
            ],
            options={
                'db_table': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_skills', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_tables.jobs')),
            ],
            options={
                'db_table': 'JobRequirements',
            },
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Applied', max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_tables.jobs')),
                ('seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_tables.jobseeker')),
            ],
            options={
                'db_table': 'JobApplications',
            },
        ),
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_tables.jobs')),
                ('seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_tables.jobseeker')),
            ],
            options={
                'db_table': 'SavedJobs',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_tables.jobseeker')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_tables.skills')),
            ],
            options={
                'db_table': 'jobseekerskills',
            },
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='seeker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_tables.users'),
        ),
    ]
