# Generated by Django 5.1.1 on 2024-10-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
