# Generated by Django 5.1.1 on 2024-10-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jobseeker.user')),
                ('company_name', models.CharField(max_length=100)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(max_length=100)),
                ('company_size', models.IntegerField()),
                ('company_address', models.CharField(max_length=255)),
                ('logo', models.URLField(blank=True, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'emp_profile',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], max_length=20)),
                ('salary_range', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('deleted', models.BooleanField(default=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeer.employerprofile')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Applied', max_length=15)),
                ('deleted', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeer.job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.jobseekerprofile')),
            ],
            options={
                'db_table': 'job_applications',
            },
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('required_skill', models.CharField(max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeer.job')),
            ],
            options={
                'db_table': 'job_requirement',
            },
        ),
    ]
