# Generated by Django 5.1.1 on 2024-10-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.TextField(default='Screw Qualifications but can you cook?'),
        ),
    ]
