# Generated by Django 5.1.1 on 2024-10-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0002_job_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(default=0),
        ),
    ]
