# Generated by Django 5.1.1 on 2024-11-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0003_alter_employerprofile_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='jobcategory',
            name='description',
        ),
    ]
