# Generated by Django 5.1.1 on 2024-10-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0003_job_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Remote', 'Remote'), ('Contract', 'Contract')], max_length=20),
        ),
    ]
