# Generated by Django 5.1.1 on 2024-10-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0006_remove_job_salary_range_job_salary_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_from',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_to',
            field=models.BigIntegerField(),
        ),
    ]
