# Generated by Django 5.1.1 on 2024-11-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0008_jobcategory_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategory',
            name='description',
        ),
    ]
