# Generated by Django 5.1.1 on 2024-11-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0009_remove_jobcategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
    ]
