# Generated by Django 5.1.1 on 2024-11-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0010_remove_job_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
