# Generated by Django 5.1.1 on 2024-11-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Jobseeker', 'Jobseeker'), ('Employer', 'Employer'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
