# Generated by Django 5.1.1 on 2024-11-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'jobseeker'), ('recruiter', 'recruiter'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
