# Generated by Django 5.1.1 on 2024-11-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_complete',
            field=models.IntegerField(default=0),
        ),
    ]
